# Generated by Django 3.2.9 on 2021-11-03 05:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('person_DOB', models.DateField(blank=True)),
                ('person_address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2021, 11, 3, 5, 49, 5, 711864))),
                ('is_complete', models.BooleanField(default=False)),
                ('end_time', models.DateTimeField(blank=True)),
                ('schedular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.person')),
            ],
        ),
    ]
